### ISSUE TITLE
unresolved import vec_collections::TotalVecMap

### ISSUE THREAD

**Issue by Horusiath** [rklaehn/vec-collections#5]
After trying to reference `vec-collections = "0.3"` and use it in following:

```rust
use vec_collections::TotalVecMap;

pub type ReplicaId = u32;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VTime(TotalVecMap<u64, [(ReplicaId, u64); 3]>);
```

what compiler complains about is:

![image](https://user-images.githubusercontent.com/679705/97808614-47b2aa80-1c68-11eb-80cf-d24bf5e570c8.png)

I assumed that total map might be featured type (btw. it's not mentioned in the documentation), so after looking into Cargo.toml, I've decided to change deps to:

```toml
[dependencies]
vec-collections = { version = "0.3", features = ["total"] }
```

But it didn't help.
